### ISSUE TITLE
To harmonize scRNA-Seq reference to align spatial data

### ISSUE THREAD

**Issue by lijinbio** [broadinstitute/Tangram#46]
Hi,

I am using Tangram to align scRNA-Seq reference onto spatial data. My scRNA-Seq reference is a collection of samples from different datasets. As a result, the raw gene expression of the scRNA-Seq reference showed a batch effect due to sample sources. May I ask if you have any suggestions to harmonize the batch effect when aligning to spatial data? Thanks.

**Comment by lewlin** [comment]
Yes - map using `cluster mode` and pass as clusters the cell types (irrespective of dataset they come from). 
See main github page, or tutorial, for how to do that (it's really just one argument to the mapping function).

What cluster mode does: it takes all cells with same label (the cluster) and average the gene expression across the cluster. The resulting averaged cell is the only cell, representative of that cluster, to be mapped to space (and clearly that can be mapped onto different spots during one alignment). The reason why this is a good idea for you, is that by doing so you average out the batch effects as the cluster will presumably contain cells from different batches.

Let me know if that is not clear and if it helps.

**Comment by lewlin** [comment]
Not the right metric: training scores merely indicate how well the model fit the data: you look at TEST scores to see which mapping works better. Indeed, it is perfectly normal that in cluster mode you have lower training scores because you are only mapping average cells therefore you have less selection (as opposed to map all cell profiles in the sc). That does not mean that mapping is less good.

About getting test scores: The strategy consists of comparing gene expression of the mapped single cells vs the spatial data across all genes _except_ those used to train Tangram. If your spatial data are Visium, typically you train on 1k markers and all the other ~29k can be used as test genes. If MERFISH you probably have few genes in your spatial data, so you want to train several times, each time with all genes except one (we call it leave-one-out-validation LOOV). The plot you are after is the one with blue dots containing sparsity of spatial data vs scores. You can automatically fit the dots with a red curve and get the resulting area under the curve (AUC). Comparing the AUCs of the two mappings is what you need (you can plot the images here and I'll help you).

You can follow the tutorial for getting test scores. LMK how that goes and if you are stuck write again.

**Comment by lijinbio** [comment]
Hi @lewlin, thank you so much for your detailed explanation. Yes, I am able to produce the test scores using LOOCV and plot the AUC images. Below is the AUC of the "cells" mode.
![BC_merfish_wt2_JC_cells](https://user-images.githubusercontent.com/16247242/145722729-e904cf38-9ab0-4239-a489-80df6c376b74.png)
And the image of the "clusters" mode is,
![BC_merfish_wt2_JC_clusters](https://user-images.githubusercontent.com/16247242/145722741-44209f59-ce85-42cd-99fa-c1849ef07e15.png)
The plot is generated for about 8,000 MERFISH cells of 73 marker genes. The AUC values are comparable between the two modes, and the "clusters" mode showed a slightly higher AUC. Given the similar AUC values, it seems that both modes are good to train full genes. To compare the two modes w.r.t. the cell type annotation by the mapping probabilities, I compared the predicted cell type labels (the deterministic label by the most scores) of two modes, and it turns out they have produced quite different annotations. For example,

![image](https://user-images.githubusercontent.com/16247242/145722933-f6331062-1ced-4ce1-8475-3faaae3a1a09.png)
In the above contingency table, the row annotation is by the "clusters" mode, and the column annotation is by the "cells" mode. The ARI of the contingency table is 0.167, i.e., two annotations are quite different. In this case, may I ask how do two modes produce quite different deterministic cell type annotations? and which annotation should I use for the downstream? Thank you so much.

**Comment by lewlin** [comment]
There you go: now that's a good comparison.

Cluster mode is giving you a _much_ better mapping (as it should, b/c of your settings): ignore cell mode mapping and just use cluster. In general, always use mapping with the highest test score. More comments:

- difference in AUCs slight but actually is very significant (we have not worked out yet a way to disentangle prediction of basal gene expression vs relevant).
- Do not trust the AUCs "too much' because the fitting we use is very crude: to compare mappings, it is helpful to overlay markers and eyeball the trends (although in your case cluster is more solid than single cell).

**Comment by lijinbio** [comment]
Hi @lewlin, that's great. Your comments are very helpful. Thank you so much for all your help.
