### ISSUE TITLE
questions on voxels and cropping spatial data

### ISSUE THREAD

**Issue by giovp** [broadinstitute/Tangram#9]
Hi,

thank you for this very cool method! very interesting paper, am finally getting around and trying out the method on Visium data.

have a couple of questions with respect to data cropping and spatial data shape

>  spatial data matrix with shape voxels-by-genes. Voxel can contain multiple cells.

what exactly is a voxel in the case of Visium?
the way I understand is that the maximum voxel is a spot, and so the spatial matrix would be of shape `(spots, genes)`. The minimum therefore would be a pixel? If that's the case, then the mapping (if perfectly converged) would be identical for all the pixels under each spot? 

Does the prior on cell density have shape `(voxels,)` ?

If the above is true, then if I have cell segmentation info for each spot, would it makes sense to generate voxels with shape `voxel_shape < spot_shape`, so to have something like: `voxel_1,voxel_2 = spot_n[0:x,:], spot_n[x:,:]`, which would make `voxel_1, voxel_2` identical in gene expression space, but with different cell density priors (e.g. 3 cells under `voxel_1` and 5 cells under `voxel_2`) ?

> I run out of memory when I map: what should I do?
Reduce your spatial data in various parts and map each single part. If that is not sufficient, you will need to downsample your single cell data as well.

this would essentially only happen with non-visium data, where there is pixel-level gene expression value ? (or yes if using an atlas as reference)

Thank you !

**Comment by lewlin** [comment]
Real thanks you for your interest giovp.

A Visium voxel is a circle with 50 um diameter which (typically) contains more than a cell. If you look at the Tangram paper, Fig 4a, grey circles defines voxel. In the voxel-by-gene data, the `x` and `y` coordinates found in the `obs` dataframe in the AnnData refer to the voxel centers (a.. "spot", if you want). Yet, the corresponding counts in the matrix `X` are obtained from all molecules within the voxel (hence, within a circle centered on the "spot" but with diameter 50 um).

You do not need any prior on cell density in order to map your data, BUT, if you wish to deconvolve (ie to obtain prediction for each single cell within a voxel) then you do.

Yes the prior on the cell density (or cell counts, you can provide either) has the shape `(voxels,)`. 

You can run out of memory with Visium data as well. If you have a lot of single cells, or you are mapping over a large portion of tissue, then you run out of RAM. If that so, we suggest to partition the dataset.

I am closing this issue, but if you think something is not clear please re-open and ask again.

Ciao,
