### ISSUE TITLE
Cell counts

### ISSUE THREAD

**Issue by spatts14** [broadinstitute/Tangram#96]
Hi! Lovely package. Apologies if its a bit of a silly question, but how do I just get the number or percent of each cells for each sample after deconvolution? I am using Nanostring GeoMX data on ROIs that were drawn (and are fairly big). I want to get the cell counts/percent cell type for each ROI.

I calculated here:
  ad_map = tg.map_cells_to_space(
                   adata_sc, 
                   adata_sp,         
                   mode='clusters',
                   cluster_label='CellType')

Thanks!

**Comment by tsvvas** [comment]
Hi @spatts14 !

This is not a silly question in my opinion, as it is not evident from the tutorial. I am not a developer of the package, but I came up with a workaround.

```python
from anndata import AnnData
from pandas import DataFrame

def get_tangram_predictions(adata: AnnData, perc=0, inplace=True) -> AnnData | DataFrame:
    tg_ct_pred = adata.obsm["tangram_ct_pred"]
    tg_ct_pred = tg_ct_pred.clip(
        tg_ct_pred.quantile(perc), tg_ct_pred.quantile(1 - perc), axis=1
    )
    tg_ct_pred = (tg_ct_pred - tg_ct_pred.min()) / (tg_ct_pred.max() - tg_ct_pred.min())

    df = DataFrame()
    df["tangram_prediction"] = tg_ct_pred.idxmax(axis=1)
    df["tangram_score"] = tg_ct_pred.apply(lambda x: max(x), axis=1)

    if inplace:
        adata.obs = adata.obs.join(df)
        return adata

    return df
```

This function is inspired by the [construct_obs_plot](https://github.com/broadinstitute/Tangram/blob/master/tangram/plot_utils.py#L163) function, which is hidden inside of the [plot_cell_annotation_sc](https://github.com/broadinstitute/Tangram/blob/master/tangram/plot_utils.py#L175) function, which plots the predicted annotations.

If you pass `inplace=True`, then the function will populate adata.obs with two new columns, called "tangram_prediction" and "tangram_score". Otherwise the function will return a dataframe with those columns.

Hope this helps,
Vasily

**Comment by spatts14** [comment]
Thanks so much for your feedback! Sorry for the late response I somehow missed this. Really appreciate your detailed work around @tsvvas
